"""fix a bag1

Revision ID: bf42434fb179
Revises: 4365cc5863a1
Create Date: 2023-09-09 20:52:57.977763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf42434fb179'
down_revision: Union[str, None] = '4365cc5863a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('operation_type', sa.String(), nullable=True))
    op.drop_column('operation', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('operation', 'operation_type')
    # ### end Alembic commands ###
